apps:
  - name        : "PCR flask"
    script      : "./daemon.shadow.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_shadow.log"
    error_file  : "log/pm2_shadow.log"

  - name        : "run sina"
    script      : "./daemon.runtime_sina.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_sina.log"
    error_file  : "log/pm2_sina.log"

  - name        : "run chat"
    script      : "./daemon.runtime_chat.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_chat.log"
    error_file  : "log/pm2_chat.log"

  - name        : "run wechat"
    script      : "./daemon.runtime_wechat.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_wechat.log"
    error_file  : "log/pm2_wechat.log"
