apps:
  - name        : "shadow PCR"
    script      : "./daemon.shadow.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_shadow.log"
    error_file  : "log/pm2_shadow.log"

  - name        : "runtime sina"
    script      : "./daemon.runtime_sina.sh"
    args        : ""
    cwd         : ""
    interpreter : "bash"
    out_file    : "log/pm2_sina.log"
    error_file  : "log/pm2_sina.log"
