[tool.poetry]
name = "pokemon"
version = "0.1.0"
description = ""
authors = ["gaoming714 <gaoming714@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.31.0"
pendulum = "^2.1.2"
Flask = "^2.3.2"
redis = "^4.5.5"
pandas = "^2.0.1"
notebook = "^6.5.4"
matplotlib = "^3.7.1"
plotly = "^5.14.1"
Envelopes = "^0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
